### ISSUE TITLE
Build script

### ISSUE THREAD

**Issue by m4rc1e** [yellow-type-foundry/xanhmono#1]
Myself, @Rosawagner and @davelab6 would like to include this family on Google Fonts. However, it is missing a build script. Here's a script you can use as a [reference](https://gitlab.com/bonjour-monde/fonderie/syne-typeface/-/blob/master/sources/build-mono.sh). You will need to edit it in order for it to work on your project.

**Comment by yellow-type-foundry** [comment]
@m4rc1e Thank you, I'll work on that.

**Comment by yellow-type-foundry** [comment]
@m4rc1e I updated the build_mono.sh file, is that OK?

**Comment by RosaWagner** [comment]
Did you export the fonts with the build script ?

**Comment by yellow-type-foundry** [comment]
@RosaWagner @m4rc1e Sorry I misunderstood your comment earlier. I have just edited the build script by Rosa and ran it on Terminal, the new font files exported with the build script are at https://github.com/yellow-type-foundry/xanhmono/tree/master/fonts. Take a look, thanks!
